name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  build-and-test:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Verify Swift Toolchain
      run: |
        swift --version
        echo Toolchain: $TOOLCHAINS
    - name: Build
      run: xcodebuild build -scheme 'SwiftUI-snapshot-testing-Package' | xcpretty
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 12 Pro' -scheme 'SwiftUI-snapshot-testing-Package' | xcpretty
