name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure Swift Toolchain
      run: |
        swift --version
        TOOLCHAINS=swift
        swift --version
    - name: Build
      run: xcodebuild build -scheme 'SwiftUI-snapshot-testing-Package' | xcpretty
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 12 Pro' -scheme 'SwiftUI-snapshot-testing-Package' | xcpretty
