name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6.1"
    - name: Verify Swift Toolchain
      run: |
        swift --version
        echo $TOOLCHAINS
    - name: Build
      run: xcodebuild build -scheme 'SwiftUI-snapshot-testing-Package' | xcpretty
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 12 Pro' -scheme 'SwiftUI-snapshot-testing-Package' | xcpretty
