name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash -l -eo pipefail {0}
jobs:
  build-and-test:
    runs-on: macos-12
    env:
      package: SwiftUI-snapshot-testing
      destination: "platform=iOS Simulator,name=iPhone 11 Pro"
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: latest
    - name: Generate Swift package Xcode project
      run: |
        swift --version
        swift package generate-xcodeproj
        xcodebuild -list
    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@master
      with:
        project: ${{ env.package }}.xcodeproj
        scheme: ${{ env.package }}-Package
        destination: ${{ env.destination }}
        action: build-for-testing
    - name: Test
      uses: sersoft-gmbh/xcodebuild-action@master
      with:
        project: ${{ env.package }}.xcodeproj
        scheme: ${{ env.package }}-Package
        destination: ${{ env.destination }}
        action: test-without-building
