name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash -l -eo pipefail {0}
jobs:
  build-and-test:
    runs-on: macos-12
    env:
      package: SwiftUI-snapshot-testing
      destination: name=iphone-12-pro
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: latest
    - name: Generate Swift package Xcode project
      run: |
        swift --version
        xcodebuild -list
        xcrun simctl create iphone-12-pro "iPhone 12 Pro"
    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        spm-package: .
        scheme: ${{ env.package }}
        destination: ${{ env.destination }}
        action: build-for-testing
    - name: Test
      uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        spm-package: .
        scheme: ${{ env.package }}
        destination: ${{ env.destination }}
        action: test-without-building
    - name: Example Test
      uses: sersoft-gmbh/xcodebuild-action@master
      with:
        project: Example/Example.xcodeproj
        scheme: Example
        destination: ${{ env.destination }}
        result-bundle-path: test-results/example-tests
        action: test
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/243
      if: always()
      run: zip -FSry results.zip test-results || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results.zip
